// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel AddRGB

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
Texture2D<float4> inTex1;
Texture2D<float4> inTex2;

[numthreads(8, 8, 1)]
void AddRGB(uint3 id : SV_DispatchThreadID)
{
	float3 re = (0*inTex1[id.xy] + inTex2[id.xy]).rgb;
	Result[id.xy] = float4(re,1);
}
