// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Init

#define PI 3.14159f

RWTexture2D<float4> Result;
int w;
int h;
RWStructuredBuffer<int> tris;

[numthreads(8, 8, 1)]
void Init(uint3 id : SV_DispatchThreadID)
{
	int i = id.x;
	int j = id.y;

	float u = i / (float)w;
	float v = j / (float)h;

	Result[id.xy] = float4(u,v,0,1);
}
//#########################################################################################################